#!/usr/bin/python

import time, subprocess, os, socket, netifaces

graphite_server = 'sever-ip'
port = 'carbon-port'
roxie_name = os.popen("service hpcc-init -c roxie status|awk '{print $1}'").readline().replace('\n', '')
ip_addr = netifaces.ifaddresses('eno1')[2][0]['addr'].replace('\n', '')
sender = socket.socket()
logfile = '/var/log/HPCCSystems/%s/roxie.log' % roxie_name
tail_it = subprocess.Popen(['tail', '-F', logfile], stdout = subprocess.PIPE, stderr = subprocess.PIPE)

sender.connect((graphite_server, port))

while True:
	msg = tail_it.stdout.readline()
	if 'COMPLETE' in msg:
		query_name = msg.split('COMPLETE:')[1].split()[0]
		time_ms = msg.split('COMPLETE:')[1].split()[6]
		query_timings = '%s.%s.%s %d %d\n' % (roxie_name, ip_addr, query_name, int(time_ms), time.time())
		sender.sendall(query_timings)
sender.close()


